### ISSUE TITLE
🗄🔧 Kotlin/Spring

### ISSUE THREAD

**Issue by agrison** [gothinkster/realworld#93] opened 2017-05-04 10:24 UTC
# Current Status

### Repository (WIP):
[agrison/realworld-kotlin-spring](https://github.com/agrison/realworld-kotlin-spring)

### Help
Come and help improve the codebase 😃 

## Todo:

- [X] 🏁 Fork the starter repo & post the link in this issue
- [X]  🎨 Create logo for repo & update issue status (@ericsimons)
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

#### Spring Data REST
I did chose not to use Spring Data REST because it gets complicated to remove the `_embedded` element as it's a fully HAL+JSON compliant library which does not work well with the API spec of the real world app project.

#### Spring Security
Regarding Spring Security, I think its too complex to implement for such a simple use case (extracting the `Authorization` header, check in db then parse the JWT).

#### Database
For the moment it uses a simple H2 in memory db, but it can be changed easily.

#### Testing
Testing needs to be implemented

**Comment by agrison** [comment] 2017-05-04 16:17
Tested it with the react frontend, seems OK.

What's the process now @SandeeshS ? Should I host a demo somewhere?

**Comment by SandeeshS** [comment] 2017-05-04 16:20
@agrison oh wow you've already completed it? :+1:  Generally you fork the repo and complete the codebase with regards to the spec. Once complete you do a thorough test and give us the go from your end, after which we test the functionality once and tag it for rfc for a peer review. After all tests pass we can move the repo here :)

**Comment by agrison** [comment] 2017-05-04 16:24
@SandeeshS Which front is the reference for testing, so that I'm sure that my tests are correct before I give you the go?

**Comment by SandeeshS** [comment] 2017-05-04 16:28
@agrison you can use any of the three referenced on the main page. React or angular is what most use to test.

**Comment by agrison** [comment] 2017-05-04 16:46
OK I'll pince you once I tested it all :)

**Comment by agrison** [comment] 2017-05-04 20:16
@SandeeshS I tested all functionalities, everything's OK from my POV 👌

**Comment by SandeeshS** [comment] 2017-05-05 03:41
@agrison awesome :+1: I've never worked with spring before. I'll get your project setup and give the api a test from my end and give you my feedback by today.

**Comment by SandeeshS** [comment] 2017-05-05 19:50
@agrison I got this setup locally and tested. I gotta say, the maven dependencies take a long time to download on windows machine. Most of the stuff seems to be working perfect except for these few things.

- Wrong error response on failed login
- No username and email validation check on registration and update
- Deleting comments throw a 404 error, but actually get deleted. Only on refresh can we see them gone.
- Comments could be sorted by latest first.

I'll try doing another round of thorough test once you've made the changes and give the :+1: from my side.

**Comment by agrison** [comment] 2017-05-05 21:39
Hi thank you for the testing. Maybe we should update the API spec because I would have known that it was needed to validate the username (alphanumeric) and email without bothering you.
I added these checks 😄 

Regarding the wrong error response on failed login, it's not clear in the spec if a 401 or a 403 is needed. I was using a 401 so I conclude that I should respond with a 403 (which I did).

Comments are now sorted correctly.

Regarding the 404 on comment deleting, I can see through postman that it correctly sends a 200 OK with no body.

The changes have been pushed.
Oh, and for maven yes the first install can take a long time, since I'm using the snapshots of spring boot they can be modified from time to time and downloaded again, but the rest should not. Once it's done, the startup should be fairly quick (like 10 seconds on my mac).

Thanks 😃

**Comment by SandeeshS** [comment] 2017-05-06 05:50
@agrison Yes i understand. I've been meaning to get the api spec re done with the validation criteria and more. But haven't been able to find the time. You're also true about the failed login. I actually did make it return a 401 on fail on laravel backend, then i had to change it to 422 with failed login message for the current frontends to make it work properly. That's how the other 3 main backends have it implemented. I had to change a lot to match with those to keep things in sync. These things are indeed important and need to be documented better.

I actually did get a 404 response on comment deleting, but they were getting deleted nonetheless. I'll pull the new changes and have another test later tonight and give you my feedback.

**Comment by agrison** [comment] 2017-05-06 06:16
OK.

So wait I'll fix the login to make it respond a 422 instead of a 401/403 ;-)

**Comment by agrison** [comment] 2017-05-06 06:39
Done 😉

**Comment by SandeeshS** [comment] 2017-05-09 14:53
@agrison Sorry for the late response, been pretty busy lately. I pulled your changes and ran another test. Here are somethings you might want to check.

- Deleting article or comment returns an invalid json response which the browser fails to handle.
- No validation check on updating user. Checks on registering works fine.
- Updating user info causes the token to become invalidated, thus causing further actions to throw unauthorized header error.

![ss 2017-05-09 at 08 15 40](https://cloud.githubusercontent.com/assets/16877877/25857002/5e1548a4-34f5-11e7-8fc8-4a57c648d6ac.png)

**Comment by agrison** [comment] 2017-05-09 15:47
Hi @SandeeshS,

Deleting a comment returns nothing in the response body and sets the ResponseCode to 200 OK :
![capture d ecran 2017-05-09 a 17 31 45](https://cloud.githubusercontent.com/assets/770753/25859054/a48e20a2-34dd-11e7-85ac-fffa630a9436.png)

So does deleting an article :
![capture d ecran 2017-05-09 a 17 32 14](https://cloud.githubusercontent.com/assets/770753/25859065/ab2841b8-34dd-11e7-9c24-3d7a0ff88dc1.png)

You're right regarding the user validation while updating, it has been implemented yesterday but I didn't push the corrections :)

Updating the user information causes the token to be re-generated only if the email has changed (since the email is stored in the JWT). What is the correct implementation for you ? For me since the token is returned from the backend, if it has changed it should be stored on the frontend localstorage and used for next requests.

I'll open an issue because testing the backend was a bit tedious with PostMan so I created a small program that test a backend implementation regarding what's said in the API spec. Maybe it can help other people, or even you 😉

**Comment by agrison** [comment] 2017-05-09 15:51
This is the tool I was talking about: https://github.com/agrison/realworld-server-tester

**Comment by SandeeshS** [comment] 2017-05-09 15:52
@agrison That sounds swell :+1: 

Well currently the token only gets stored in sign in, therefore token changes later wouldn't reflect. The ideal situation would be to use single request token as per the JWT standards. But this project doesn't require that high level of security since it's more like a starter, or that's what the idea was when the spec was first created. So i'd suggest not to invalidate the token at least to keep in sync with the other implementations. Btw none of the JWT claims are actually used by the frontend, it only cares and uses the token as a whole. So i'd even recommend not storing anything in the JWT apart from the standard claims.

As for the delete response errors, can you test with a local frontend setup? I have attached the error that i received on chrome using the angular frontend.

**Comment by agrison** [comment] 2017-05-09 16:03
Ok for the JWT sounds ok for me.

I think the problem for article delete + comment delete are finished.

Delete comment:
<img width="503" alt="capture d ecran 2017-05-09 a 18 00 34" src="https://cloud.githubusercontent.com/assets/770753/25860378/a97912a8-34e1-11e7-81d7-a0cc1b3729b3.png">
<img width="739" alt="capture d ecran 2017-05-09 a 18 00 52" src="https://cloud.githubusercontent.com/assets/770753/25860418/c804c186-34e1-11e7-8c32-0d173b72e032.png">

Delete article:
<img width="439" alt="capture d ecran 2017-05-09 a 18 01 32" src="https://cloud.githubusercontent.com/assets/770753/25860436/d0541454-34e1-11e7-8e6d-aece8e9ec9e8.png">
<img width="749" alt="capture d ecran 2017-05-09 a 18 01 14" src="https://cloud.githubusercontent.com/assets/770753/25860440/d54ea6cc-34e1-11e7-8010-fef5c98b0ad0.png">

No errors in the console at all.

**Comment by SandeeshS** [comment] 2017-05-09 16:05
@agrison cool, let me know when i can pull the latest changes and test it out one last time :)

**Comment by agrison** [comment] 2017-05-09 19:01
Well you can 😄

**Comment by SandeeshS** [comment] 2017-05-09 19:34
Ran another test. All the other stuff is fixed and working as intended. The error on deleting article and comment seems to be something with the angular frontend. It's failing to parse the empty json response. Tried with chrome and ff and it's the same. You may look into it if you have the time.

All the tests have passed from my side :+1:

**Comment by agrison** [comment] 2017-05-09 19:55
Well its not specified in the API spec if deleting an article should return something or not. I made it return nothing, but it's easy to return anything else. For example the deleted article 😉 
Same story for comment deletion 👍

**Comment by EricSimons** [comment] 2017-05-10 03:16
@agrison yeah the API spec is currently a bit flawed (100% entirely my + @apai4's fault, putting this project together was a huge task and we unintentionally cut corners). @SandeeshS has been working on a new version though that is really thorough & detailed, which should fix problems like these 💯 

Regarding the codebase, things are looking good on my end as well. It would be great to have a Kotlin/Spring community member review the codebase to ensure it follows best practices/etc — do you know any off hand? No worries if not; I can try and chase some folks down :)

**Comment by agrison** [comment] 2017-05-10 05:38
Like I said I only played with Kotlin for some time, I'm more versed into Java, Clojure or other languages. It was mainly for a fun experiment 😃 
If you know people who can to take a look and/or participate that would be great to learn. As always there's always some code to remove, improve or change to make it more idiomatic 😉

**Comment by EricSimons** [comment] 2017-05-16 22:05
Awesome work!! Just created the official repo (https://github.com/gothinkster/kotlin-spring-realworld-example-app) and added @agrison as a collaborator/admin! Also added it to the main README :)

Closing this issue; any future discussions should happen over at https://github.com/gothinkster/kotlin-spring-realworld-example-app/issues 👍

**Closed by EricSimons** 2017-05-16 22:05 UTC
Labels: backend, rfc
