### ISSUE TITLE
[Bug]: CORS Error

### ISSUE THREAD

**Issue by parhamsagharchi** [gothinkster/realworld#1327] opened 2023-06-25 15:21 UTC
### Relevant scope

Frontend specs

### Description

Hi, 

I have been using these APIs for my interview task, I faced a CORS error with this endpoint `POST /api/users`.

Also, I checked on your demo [website](https://demo.realworld.io/#/register),  but unfortunately, I won't register my user with that website.

could you fix this problem?

Thank You,
Parham

**Comment by geromegrignon** [comment] 2023-06-25 20:48
Hi Parham. The API was down. I fixed it.
You should not face CORS issues by design. Feel free to tell me if there is still an issue.

Is using RealWorld a requirement for the interview? I'm curious as not having that much information about how the API is used outside of the project itself.

**Comment by sarinaa-m** [comment] 2023-12-21 17:00
Hi 
I having the same issue and when I want to call POST /api/users I get CORS error

would you mind help me.

**Comment by geromegrignon** [comment] 2023-12-21 17:01
Hi @sarinaa-m, can you share the full error message?

**Comment by sarinaa-m** [comment] 2023-12-21 17:03
yes of course
![Capture1](https://github.com/gothinkster/realworld/assets/77147291/c076d15e-1e78-4585-8e93-c2a3b00c95c7)

**Comment by geromegrignon** [comment] 2023-12-21 17:04
I only see the failure, please share the error message explaining that's a cord error

**Comment by sarinaa-m** [comment] 2023-12-21 17:06
is it ok?
![Capture2](https://github.com/gothinkster/realworld/assets/77147291/7cb91b0d-5def-49de-b6b7-f4f5af279054)

**Comment by sarinaa-m** [comment] 2023-12-21 17:11
thank you for answering my question 
but I fixed it
I added withCredentials: true, to my axios config, and when I removed it, it worked.

**Comment by geromegrignon** [comment] 2023-12-21 17:19
Happy that's fixed on your side!
The API is allowing any origin intentionally.

**Closed** 2024-08-09 22:24 UTC
Labels: bug
