### ISSUE TITLE
Implement Vue Realworld with Pug templates

### ISSUE THREAD

**Issue by Branksy** [gothinkster/realworld#160] opened 2017-12-06 15:08 UTC
Why is vue/realworld not being implemented with Pug in templates? It would be much more readable (esp. in longer files with a lot of code logic)

**Comment by disjfa** [comment] 2017-12-06 19:48
The issue is better placed in the realworld-vue issue list, https://github.com/vilsbole/realworld-vue/issues

But as for me, i find pug not readable and i like html, because we build html. But thats just an opinion. And as for it's for learning vue, so we don't need to learn a new template language. But a custom vue+pug version can be created.

**Comment by andreoav** [comment] 2017-12-20 10:51
I agree with @disjfa 

If this is a comparison between each framework, the default stack should be used.

**Comment by Cameron-C-Chapman** [comment] 2018-01-09 01:46
I agree with @disjfa, this feels like something that would fit better in the issues in the https://github.com/vilsbole/realworld-vue/issues repo. I'm going to go ahead and close this. Let me know if you disagree and you'd like the discussion re-opened @Branksy.

**Closed by Cameron-C-Chapman** 2018-01-09 01:46 UTC
