### ISSUE TITLE
[Bug]: Several times add number "favorited"

### ISSUE THREAD

**Issue by AlinkLiy** [gothinkster/realworld#922] opened 2022-04-12 12:34 UTC
### Relevant scope

Frontend specs

### Description

Steps to reproduce:
1) For example, move to Gerome's blog (https://demo.realworld.io/#/@Gerome) 

2) Click a few times (for example, 5 times) on the button "favorited".

3) Wait.

**Actual result**: The number "favorited" has increased by 5 on the page and the browser sends 5 requests.
**Expected result:** The number "favorited" has increased by 1 on the page and the browser sends 1 requests.

_Before steps to reproduce:_
<img width="935" alt="Снимок экрана 2022-04-12 в 15 03 57" src="https://user-images.githubusercontent.com/40720633/162958622-94c44ad5-d80c-4ba4-8736-0f5401bdd367.png">

_After steps to reproduce:_
<img width="935" alt="Снимок экрана 2022-04-12 в 15 04 55" src="https://user-images.githubusercontent.com/40720633/162958774-3f621066-f91b-43a9-addc-8612937d7860.png">

When I reload this page, the number "favorited" increases by only 1 (on the picture).

<img width="978" alt="Снимок экрана 2022-04-12 в 14 25 01" src="https://user-images.githubusercontent.com/40720633/162949853-f5e71ec1-3d6c-4668-b6b2-2345464b20d3.png">

I think it happens because the button "favorite" isn't disabled after it has been clicked (shown on the picture). 

<img width="1440" alt="Снимок экрана 2022-04-12 в 15 34 00" src="https://user-images.githubusercontent.com/40720633/162963330-cd73333f-03b2-4b7a-93f0-b33141ba32a8.png">

**Comment by geromegrignon** [comment] 2022-04-13 14:22
Hi @AlinkLiy, 

Thanks for reporting this issue.
I'll work on z fix later on this week.

Can you tell me which frontend implementation was used for the screenshot? The api url is now api.realworld.io and it's still about the conduit.productionready.io one.

**Comment by geromegrignon** [comment] 2022-04-20 13:10
@AlinkLiy,

I can't reproduce this bug with the API and several frontend implementations.
It's more likely due to the implementation you used: 
this implementation increments a counter on each click rather than on the real favorite counter.

Can you provide a link to this implementation?

**Comment by geromegrignon** [comment] 2022-05-20 15:37
Closing the issue as no info has been provided yet.
Feel free to add a comment later on.

**Closed by geromegrignon** 2022-05-20 15:37 UTC
Labels: bug
