### ISSUE TITLE
The reference backend is not responding

### ISSUE THREAD

**Issue by mvila** [gothinkster/realworld#700] opened 2021-07-29 22:17 UTC
The reference backend (https://conduit.productionready.io/api) is not responding and therefore most [frontend implementations](https://codebase.show/projects/realworld) are broken! 😢 

We are desperately trying to contact the maintainer of this backend and find a solution as soon as possible.

We are very sorry for the inconvenience. Thank you for your patience.

**Comment by xuchaobei** [comment] 2021-07-31 09:32
Is there any progress ?

**Comment by tiagon97** [comment] 2021-07-31 15:46
Yesterday was ok, today seems that problem still exists.

**Comment by mvila** [comment] 2021-07-31 22:50
Right now, the backend is responding normally. It is possible that it is under an intermittent DoS attack. We could reach the maintainer, but, unfortunately, he will not be able to do anything before Monday.

**Comment by Allianzcortex** [comment] 2021-08-03 15:02
it used to be totally broken but now it seems fixed but hanging forever. Thanks for all ur efforts to maintain this backend implementation ( : -

**Comment by Roynet825** [comment] 2021-08-03 17:09
Still very slow, hardly get data from API...

**Comment by Allianzcortex** [comment] 2021-08-10 18:52
> Still very slow, hardly get data from API...

Yeah , only works occasionally and unstable. One suggestion here is to run a daemon scripts every day to keep posts amount below the threshold since this is an API used for demonstrating the usage of frameworks rather than a real commercial one. ( prerequisite is that we can get the access tho ( :-

**Comment by mvila** [comment] 2021-08-10 21:34
@apai4 I think you are in charge of this backend and we really need your help there. If you are too busy to take care of it, could you please give us (@geromegrignon or me) access to the subdomain `conduit.productionready.io` so that we can deploy a new backend? Or, if you prefer, we can deploy a new backend first and you'd just have to make the necessary changes so that `conduit.productionready.io` points to it. You can reach me at hi@mvila.me. Thanks.

**Comment by geromegrignon** [comment] 2021-08-11 00:14
> > Still very slow, hardly get data from API...
> 
> Yeah , only works occasionally and unstable. One suggestion here is to run a daemon scripts every day to keep posts amount below the threshold since this is an API used for demonstrating the usage of frameworks rather than a real commercial one. ( prerequisite is that we can get the access tho ( :-

Indeed, the purpose of this API is to provide a demo.
But no update occurred since it was released a few years ago.

We don't plan to move it to a more scalable solution (for money reasons).
But I want to create a [webcontainer sample](https://blog.stackblitz.com/posts/introducing-webcontainers/) with stackblitz to provide a way to run locally an API as a workaround (with the benefit of running into the browser without installation requirements).

**Comment by Allianzcortex** [comment] 2021-08-11 02:19
@geromegrignon yeah , makes sense aboslutely. BTW there's lots of NSFW tags now...  
![image](https://user-images.githubusercontent.com/7290780/128959638-ada3394e-42ff-4650-9175-381c29d1e8d1.png)

**Comment by Postavshik** [comment] 2021-08-12 13:36
@geromegrignon 
Could you provide the source code to the backend of conduit.productionready.io/api? Better if there would be a Docker container that anyone can spin up on the localhost and use for application without calling actual API.
Thumbs up if you like the idea.

**Comment by geromegrignon** [comment] 2021-08-13 20:20
> @geromegrignon
> Could you provide the source code to the backend of conduit.productionready.io/api? Better if there would be a Docker container that anyone can spin up on the localhost and use for application without calling actual API.
> Thumbs up if you like the idea.

It's an awesome idea!

The deployed backend is from the rails implementation: https://github.com/gothinkster/rails-realworld-example-app/tree/master

**Comment by Postavshik** [comment] 2021-08-14 23:14
@geromegrignon 
Thank you for the repo! I was trying to run it on my Mac, unfotunately no luck... Looks like it's too old and have bunch of old dependencies that have compatibility issues..
As far as I was able to go is just successfully make "bundle install" using Ruby 2.6.4 and rails 4.2.6. But stuck on "rake db:migrate" with error "rake aborted!" and any meaningful descriptoion why.

I have tried the branch "rails-5.1" brans but that didn't work because it has a reference to the repo that does not exist anymore, which is this one "https://github.com/gogovan/devise.git"

Could you maybe take a look in the project and check if it's possible to update to make it work? Then I can try to wrap it into Docker and publish the image.

**Comment by Allianzcortex** [comment] 2021-08-15 00:00
> @geromegrignon
> Thank you for the repo! I was trying to run it on my Mac, unfotunately no luck... Looks like it's too old and have bunch of old dependencies that have compatibility issues..
> As far as I was able to go is just successfully make "bundle install" using Ruby 2.6.4 and rails 4.2.6. But stuck on "rake db:migrate" with error "rake aborted!" and any meaningful descriptoion why.
> 
> I have tried the branch "rails-5.1" brans but that didn't work because it has a reference to the repo that does not exist anymore, which is this one "https://github.com/gogovan/devise.git"
> 
> Could you maybe take a look in the project and check if it's possible to update to make it work? Then I can try to wrap it into Docker and publish the image.

ROR is a great framework , but if you just want an available backend here I will recommend https://github.com/err0r500/go-realworld-clean which uses the full binary-compatiable advantage of go. You just need 2 commands `go build & go run main.go` and you can run in any machines. There is a docker one and you may also wanna have a try : https://github.com/raahii/golang-grpc-realworld-example

**Comment by geromegrignon** [comment] 2021-08-17 12:13
@Postavshik I never used Ruby so I won't be that useful.

I'm fine with creating the docker image with another backend listed on [CodebaseShow](https://codebase.show/projects/realworld?category=backend).
Just make sure it passes the Postman collection tests (instructions [here](https://github.com/gothinkster/realworld/tree/master/api)).

@cirosantilli made a great contribution to improve it to tests backend implementations.

**Comment by cirosantilli** [comment] 2021-08-17 13:00
BTW, I would recommend using a Node.js + Express.js + Sequelize as the reference due to the popularity of Node.js and the other elements of the that stack. I think Node.js is already making/will inevitably make Ruby/Rails disappear moving forward. Uber subjective of course.

This is the backend I've been using: https://github.com/cirosantilli/node-express-sequelize-realworld-example-app and which works out of box on Ubuntu 21.04 and passes all postman tests.

Sequelize over mongodb is more portable, in particular since mongo now has licensing issues, so is not being shipped anymore on major distros as easily.

**Comment by geromegrignon** [comment] 2021-08-17 13:30
I was indeed considering Node.js + Express.js.
About the ORM, I was taking a look at Prisma as an alternative.

**Comment by geromegrignon** [comment] 2021-08-22 00:27
Quick update,

I'm working on a new backend implementation to deploy it as soon as possible.
It'll be a temporary solution while waiting for access to the real-world domain.

I still have some bugs to fix (the postman collection helping me a lot):
![image](https://user-images.githubusercontent.com/32737308/130338064-0923bf60-ce9e-4713-94e1-17bf2bdd3fd5.png)

Once live, I'll update the documentation.

**Comment by geromegrignon** [comment] 2021-08-23 06:58
Here is the URL of the new API: https://realworld-temp-api.herokuapp.com/api
Keep in mind it's a temporary one. The goal is to deploy it to the existing productionready.io domain for existing implementations relying on it.
The API is deployed for free on Heroku, meaning the server sleeps after 30 minutes of inactivity.
So you may encounter latency on the first request on it (few seconds). 

Besides applying to the current specs, this API includes:
- a cron deleting all articles on Sundays
- a rate limitation (500 requests every 15 minutes)
- a swagger UI to test the API on https://realworld-temp-api.herokuapp.com/api-docs

related to #708

### Make it work, make it right, make it fast

#### Make it work
The new API passes the Postman collection.
Would you please open an issue if you find out a bug?

#### Make it right
I'll spend next week cleaning the code.
Once done, I'll open source it.

#### Make it fast
As explained earlier, the API sleeps after 30 minutes of inactivity.
Please open an issue if you encounter any additional latency on requests.

**Comment by Allianzcortex** [comment] 2021-08-23 12:04
> Here is the URL of the new API: https://realworld-temp-api.herokuapp.com/api
> Keep in mind it's a temporary one. The goal is to deploy it to the existing productionready.io domain for existing implementations relying on it.
> The API is deployed for free on Heroku, meaning the server sleeps after 30 minutes of inactivity.
> So you may encounter latency on the first request on it (few seconds).
> 
> Besides applying to the current specs, this API includes:
> 
> * a cron deleting all articles on Sundays
> * a rate limitation (500 requests every 15 minutes)
> * a swagger UI to test the API on https://realworld-temp-api.herokuapp.com/api-docs
> 
> related to #708
> 
> ### Make it work, make it right, make it fast
> #### Make it work
> The new API passes the Postman collection.
> Would you please open an issue if you find out a bug?
> 
> #### Make it right
> I'll spend next week cleaning the code.
> Once done, I'll open source it.
> 
> #### Make it fast
> As explained earlier, the API sleeps after 30 minutes of inactivity.
> Would you please open an issue if you encounter any additional latency on requests?
> 
> #### Limitations
> The API is deployed on a free account on Heroku with row and connection limits.
> Thanks to sponsors, the plan is to move to a production solution on Heroku while limiting the costs.
> Meanwhile, please keep in mind this new API is a workaround for current issues.

awesome job ! ！ I just update my project with new API here : https://react-typescript-hooks-realworld.vercel.app/ and find that for retrieving feed&tags , we still need to get authorized.  This seems an unexpected behaviour ? 
![image](https://user-images.githubusercontent.com/7290780/130444107-b544bf85-8683-4120-ad8f-5b0c0a9cf00a.png)

**Comment by geromegrignon** [comment] 2021-08-23 12:15
@Allianzcortex 
Authentication isn't required on the feed (global feed, the personal feed still need authentication) and on tags.
I can't reproduce it on Postman and by using the swagger on https://realworld-temp-api.herokuapp.com/api-docs

**Comment by Allianzcortex** [comment] 2021-08-23 12:21
@geromegrignon yeah,very weird one. After cleaning up my old token and it works well. NVM ( - :

**Comment by geromegrignon** [comment] 2021-08-23 12:23
@Allianzcortex 

I still need to fix: 
- personal feed not retrieving data
- tags not being deleted on article deletion

**Comment by Allianzcortex** [comment] 2021-08-23 13:26
@geromegrignon feel it's better if we open another issue for the new API discussion. Here just curious that, for comments, the return format is :
![image](https://user-images.githubusercontent.com/7290780/130454603-a5617f0c-4cf1-44af-88d8-fbc3133a20bf.png)

`{"comments":{"comments":[]}}`

If it has passed all the postman tests then it should be np , but I feel it may be :  

`{"comments":[]}`

My current implementation is broken for this 
![image](https://user-images.githubusercontent.com/7290780/130455206-416b328f-6613-4bb5-ab40-dcf23f42f075.png)

it says `map is not a function`.

**Comment by geromegrignon** [comment] 2021-08-23 13:34
@Allianzcortex I fixed it.

**Comment by geromegrignon** [comment] 2021-08-23 13:45
You can submit and track issues related to this new API on #712

**Comment by geromegrignon** [comment] 2021-09-28 12:34
Resolved with a new API release.

**Closed by geromegrignon** 2021-09-28 12:34 UTC
